# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f11e647a902df42cc452f83123005416a4c5e7d332a588cce991c1c433cb533130eb4e960d9c362cf4daa741a0457b4c29083e7d06f377563c46dd92b618d119

test:
  secret_key_base: 2144708ad2f69986d03283c7209a11baa24603b19afa8058b698b2d39ffd2804243b3fb3072d0ee483187e9ccb8ab09cf42dd60abdaca9747b2d2f24856720a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
